language: ruby
cache: bundler
env:
  global:
    - PUPPET_VERSION='~> 5.0'
matrix:
  include:
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=centos7 BEAKER_debug=true
    script: bundle exec rake test beaker
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=xenial BEAKER_debug=true
    script: bundle exec rake test beaker
